// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwnoodnesjuomfuajdvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bm9vZG5lc2p1b21mdWFqZHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Mjk3MjIsImV4cCI6MjA3MjUwNTcyMn0.eo_rJknmeCNHf5XE3JYNa1ZzU4M5ugD74EM3ysy6UGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});